[package]
name = "simd-sexp"
version = "0.1.0"
authors = ["Cheng Sun <_@chengsun.uk>"]
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
ocaml = "0.22"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "extract"
harness = false

[[bench]]
name = "find_quote_transitions"
harness = false

[[bench]]
name = "lib"
harness = false

[[bench]]
name = "start_stop_transitions"
harness = false

[[bench]]
name = "vector_classifier"
harness = false

[[bench]]
name = "xor_masked_adjacent"
harness = false
